modmap:
  - name: Global
    remap:
      # CapsLock to Ctrl
      CapsLock: LeftCtrl
      # Swap Alt and Meta
      LeftAlt: LeftMeta
      LeftMeta: LeftAlt

keymap:
  - name: Global
    remap:
      # Ctrl+[ to Esc like Vim
      LeftCtrl-Leftbrace: Esc

      # Ctrl+h to Backspace
      LeftCtrl-h: Backspace

      # Alt+hjkl to arrow keys
      LeftAlt-h: Left
      LeftAlt-j: Down
      LeftAlt-k: Up
      LeftAlt-l: Right

      # zoom in/out
      LeftMeta-Shift-Equal: C-Shift-Equal
      LeftMeta-Shift-Minus: C-Shift-Minus
      LeftMeta-0: C-0

  - name: Non-Terminal
    application:
      not: [wezterm]
    remap:
      # Mac-like key bindings
      LeftMeta-c: C-c
      LeftMeta-v: C-v
      LeftMeta-t: C-t
      LeftMeta-w: C-w
      LeftMeta-f: C-f
      LeftMeta-l: C-l
      LeftMeta-z: C-z
      LeftMeta-r: C-r
      # +Shift
      LeftMeta-Shift-t: C-Shift-t
      LeftMeta-Shift-z: C-Shift-z

  - name: Terminal
    application:
      only: [wezterm]
    remap:
      LeftMeta-c: C-Shift-c
      LeftMeta-v: C-Shift-v
      LeftMeta-t: C-Shift-t
      LeftMeta-w: C-Shift-w
