#!/usr/bin/env bash

set -eu -o pipefail

options=(
  --dockerfile Dockerfile
  # --env-file .env
  # Use shared volume for package cache
  --volume agent-sandbox--global--home-npm:/home/node/.npm
  # --volume agent-sandbox--global--home-cache-yarn:/home/node/.cache/yarn
  --mount-readonly ~/.gitconfig:/home/node/.gitconfig
  --allow-write
)

# Create volumes for each node_modules directory
options+=("--volume" "node_modules")
find packages -type d -mindepth 1 -maxdepth 1 -print0 | while IFS= read -r -d '' path; do
  options+=("--volume" "$path/node_modules")
done

# Mount original git repository when using worktree
git_root=$(git rev-parse --show-toplevel)
if test -f "$git_root/.git"; then
  git_original_root=$(sed -E 's,^gitdir: (.+)/.git/.+,\1,' < "$git_root/.git")
  options+=("--mount-writable" "$git_original_root:$git_original_root")
fi

agent-sandbox "${options[@]}" "$@"
