model_list:
  - model_name: gemini-3-flash-preview
    litellm_params:
      model: vertex_ai/gemini-3-flash-preview
      vertex_project: os.environ/VERTEXAI_PROJECT
      vertex_location: global
      # https://docs.litellm.ai/docs/pass_through/vertex_ai
      # use_in_pass_through: true

  - model_name: claude-haiku-4-5
    litellm_params:
      model: bedrock/global.anthropic.claude-haiku-4-5-20251001-v1:0
      aws_region_name: ap-northeast-1
      # https://docs.litellm.ai/docs/pass_through/bedrock
      # custom_llm_provider: bedrock
