#!/usr/bin/env bash

set -eu -o pipefail

this_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Setup container environment
"$this_dir/run" --verbose --allow-net 0.0.0.0/0 npm ci

# Setup host
npm ci
